name: Deployment
on: push
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup git config
        run: |
          git config --global user.email rboyko94@gmail.com
          git config --global user.name roman-boyko
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test app
        run: npm run test
      - name: Deploy app
        run: npm run deploy
