name: Deployment
on: push
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup git config
        run: |
          git config user.name "Roman Boyko"
          git config user.email "rboyko94@gmail.com"
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test app
        run: npm run test
      - name: Deploy app
        run: npm run deploy
